//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace features.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Symptoms = new HashSet<Symptom>();
        }
    
        public int departmentsId { get; set; }

        [Required(ErrorMessage = "Department Name is Required")]
        [DataType(DataType.Text, ErrorMessage = "No numbers are allowed. Please enter text.")]
        [Display(Name = "Name")]
        public string dptName { get; set; }

        [Required(ErrorMessage = "Department Description is Required")]
        [DataType(DataType.Text, ErrorMessage = "No numbers are allowed. Please enter text.")]
        [Display(Name = "Description")]
        public string dptDesc { get; set; }
    
        public virtual ICollection<Symptom> Symptoms { get; set; }
    }
}
