//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace features.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feeedback
    {
        public int feedbackId { get; set; }

/*        [Required(ErrorMessage = "First Name is Required")]
        [DataType(DataType.Text, ErrorMessage = "No numbers are allowed. Please enter text.")]*/
        [Display(Name = "First name")]
        public string firstName { get; set; }

/*        [Required(ErrorMessage = "Last Name is Required")]
        [DataType(DataType.Text, ErrorMessage = "No numbers are allowed. Please enter text.")]*/
        [Display(Name = "Last name")]
        public string lastName { get; set; }

/*        [Required(ErrorMessage = "Email is Required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Please enter a correct email format.")]*/
        [Display(Name = "Email")]
        public string email { get; set; }

 /*       [Required(ErrorMessage = "Subject is Required")]
        [DataType(DataType.Text, ErrorMessage = "No numbers are allowed. Please enter text.")]*/
        [Display(Name = "Subject")]
        public string subject { get; set; }

        public Nullable<System.DateTime> timestamp { get; set; }

/*        [Required(ErrorMessage = "Feedback is Required")]
        [DataType(DataType.Text, ErrorMessage = "No numbers are allowed. Please enter text.")]*/
        [Display(Name = "Feedback")]
        public string feedback { get; set; }
    }
}
