//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace features.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetaByteContext : DbContext
    {
        public PetaByteContext()
            : base("name=PetaByteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Feeedback> Feeedbacks { get; set; }
        public DbSet<Symptom> Symptoms { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<HospitalEvent> HospitalEvents { get; set; }
    }
}
