//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace features.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public int symptomsId { get; set; }
        public string symptName { get; set; }
        public Nullable<int> deptId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
